default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mysql
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: sdvx_stats_development

test:
  <<: *default
  database: sdvx_stats_test

production:
  <<: *default
  database: sdvx_stats_production
  password: <%= ENV['DB_PWD'] %>
